### PR TITLE
chore: upgrade micronaut → `4.4.x`

### PR DESCRIPTION
**Pull request by sgammon**
Ready for review [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=elide-dev&utm_campaign=badge_info)

## Summary

- chore: upgrade micronaut
- chore: re-gen lockfiles
- chore: update verification metadata

### CODE REVIEW

**Review by WolfTheDeveloper — COMMENTED** [review]
ig. just looks like a bunch of number changes and i was requested. doesn't look like anything will break.

**Comment by WolfTheDeveloper** [comment]
> ig. just looks like a bunch of number changes and i was requested. doesn't look like anything will break.

I also hate notifications and emails in my inbox

**Comment by sgammon** [comment]
@WolfTheDeveloper oh, sorry, we probably just need to adjust the teams so you don't get pinged for these. @darvld can review

> just looks like a bunch of number changes and i was requested. doesn't look like anything will break.

It's just a version bump, of [Micronaut](https://micronaut.io), one of our core dependencies. We use two features in Gradle, [Dependency Locking](https://docs.gradle.org/current/userguide/dependency_locking.html) and [Dependency Verification](https://docs.gradle.org/current/userguide/dependency_verification.html), which help lock down our dependencies. We do this because:

- It prevents "drift" of dependencies -- everyone locks to the same version, which is declared within the repo, and can be consulted or inspected
- It prevents developers getting different dependencies, via checksum verification
- It prevents developers getting unauthorized malicious dependencies, via signature checks

So, the actual "meat" of this change is in `gradle/elide.versions.toml` (https://github.com/elide-dev/elide/pull/925/files#diff-a970e09ff04794b238ca60220cd830790065f3bed049991d1f5f5fa45abb2ad2), which changes the dependency versions. In this case, Micronaut also needs a property change ([here](https://github.com/elide-dev/elide/pull/925/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19)) because we use it at build-time, as part of our build (i.e. Gradle plugins), not just at runtime.

Everything else in this change is just noise: verification metadata, lockfile changes, and formatting fixes.

**Comment by WolfTheDeveloper** [comment]
> @WolfTheDeveloper oh, sorry, we probably just need to adjust the teams so you don't get pinged for these. @darvld can review
> 
> 
> 
> > just looks like a bunch of number changes and i was requested. doesn't look like anything will break.
> 
Its fine.

**Review by darvld — APPROVED** [review]
lgtm 👍

**Pull request merged**
